stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: trion/ng-cli
  allow_failure: false
  before_script:
    - npm ci
  script:
    - ng build --prod
  artifacts:
    expire_in: 2 hours
    paths:
      - dist/
  only:
    - dev
  tags:
    - test

variables:
  CLI_VERSION: 6.2.1

test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  before_script:
    - npm ci
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm test
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  tags:
    - test


test:e2e:
  stage: test
  image: trion/ng-cli-e2e:${CLI_VERSION}
  allow_failure: false
  before_script:
    - npm ci
  script:
    - ng e2e
    - echo "Launch end-to-end test"
  tags:
    - test

