---
# Include variables and define needed variables.
- name: Debian | Include OS-specific variables.
  include_vars: "main.yml"

- name: Add DotDeb Key
  become: true
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present

- name: Add DotDeb to repository
  become: true
  apt_repository:
    repo: deb http://packages.dotdeb.org jessie all
    state: present

- name: Add DotDeb Src to repository
  become: true
  apt_repository:
    repo: deb-src http://packages.dotdeb.org jessie all
    state: present

- name: PHP install
  become: true
  apt: 
    name: "{{ php_packages }}"
    state: latest
    update_cache: yes

- name: Security
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: 'disable_functions[\s]?='
    line: 'disable_functions = exec,passthru,shell_exec,proc_open,popen'
- lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: 'upload_max_filesize[\s]?='
    line: 'upload_max_filesize = {{ php_upload_max_filesize }}'
- lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: 'memory_limit[\s]?='
    line: 'memory_limit = {{ php_memory_limit }}'
- lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: 'date.timezone[\s]?='
    line: 'date.timezone = {{ php_timezone }}'
    notify: php restart
