---
# Include variables and define needed variables.
- name: Debian | Include OS-specific variables.
  include_vars: "default.yml"

- name: Nginx install
  become: true
  apt:
    name: nginx
    state: latest

- name: Start Nginx
  become: true
  service:
    name: nginx
    state: started
    enabled: true

- name: Remove old Nginx conf
  file:
    path: ['/etc/nginx/sites-enabled/default', '/etc/nginx/sites-available/default']
    state: absent
  become: yes

- name: Create new Nginx conf
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-available/back.testlab.com
  become: yes

- name: Active domain
  file:
    src: /etc/nginx/sites-available/back.testlab.com
    dest: /etc/nginx/sites-enabled/back.testlab.com
    state: link
  become: yes

- name: Nginx restart
  service:
    name: nginx
    state: restarted

- name: PHP install
  become: true
  apt: 
    name: "{{ php_packages }}"
    state: latest
    update_cache: yes

- name: Security
  lineinfile:
    dest: /etc/php/7.3/apache2/php.ini
    regexp: 'disable_functions[\s]?='
    line: 'disable_functions = exec,passthru,shell_exec,proc_open,popen'
- lineinfile:
    dest: /etc/php/7.3/apache2/php.ini
    regexp: 'upload_max_filesize[\s]?='
    line: 'upload_max_filesize = {{ php_upload_max_filesize }}'
- lineinfile:
    dest: /etc/php/7.3/apache2/php.ini
    regexp: 'memory_limit[\s]?='
    line: 'memory_limit = {{ php_memory_limit }}'
- lineinfile:
    dest: /etc/php/7.3/apache2/php.ini
    regexp: 'date.timezone[\s]?='
    line: 'date.timezone = {{ php_timezone }}'
