---
- include: ../../back/tasks/nginx.yml
  vars:
    current_host: "{{ hostname.front }}"

- name: Install NodeJS
  apt: 
    name: nodejs
    update_cache: yes
    state: latest

- name: Install Npm
  apt: 
    name: npm
    update_cache: yes
    state: latest

- name: Install PM2
  npm:
    name: pm2
    global: yes

- name: Install Angular.js
  become: yes
  npm:
    name: "@angular/cli"
    global: yes
    state: present

- name: Git Clone Repo
  git: 
    repo: "{{ front_repository }}"
    dest: "/var/www/{{ hostname.front }}"

- name: Install packages based on package.json
  npm:
    path: "/var/www/{{ hostname.front }}"
    state: latest

- name: Create new prod env conf
  template:
    src: templates/prod.j2
    dest: "/var/www/{{ hostname.front }}/src/environments/environment.prod.ts"
  become: yes

- name: Build Angular app
  command: ng build --prod
  args:
    chdir: "/var/www/{{ hostname.front }}"
