stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: trion/ng-cli
  allow_failure: false
  before_script:
    - npm i
  script:
    - ng build --prod
  artifacts:
    expire_in: 2 hours
    paths:
      - dist/

variables:
  CLI_VERSION: 6.2.1

test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  before_script:
    - npm i
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm test

test:e2e:
  stage: test
  image: trion/ng-cli-e2e:${CLI_VERSION}
  allow_failure: false
  before_script:
    - npm i
  script:
    - ./node_modules/protractor/bin/webdriver-manager update --versions.chrome
    - ng e2e --webdriver-update=false

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "ansible-playbook -i devops-86/ansible/hosts devops-86/ansible/deployement/front/playbook.yml"
  environment:
    name: production
    url: http://front.test.com
  only: 
    - master
