---
- name: Install global servers
  hosts: all
  remote_user: root

  tasks:
    - name: Set environement variables
      include_vars: env_vars.yml

    - name: Install prerequies
      apt: 
        name: aptitude        
        state: latest
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes


- name: Install database server
  hosts: database
  remote_user: root

  pre_tasks:
    - name: Generate secure password
      set_fact:
        password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

  roles:
    - role: mysql
      db_password: "{{ password }}"  

- name: Install back server
  hosts: back
  remote_user: root

  roles:
    - role: back
      db_password: "{{ hostvars[groups['database'][0]]['password'] }}"

- name: Install front server
  hosts: front
  remote_user: root

  roles:
    - front